# Generated by Django 2.2 on 2019-04-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Activity_Monitoring', '0002_auto_20190418_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_change_task_status', 'Can change task status'),), 'verbose_name': 'is_finished'},
        ),
    ]
