# Generated by Django 2.2 on 2019-04-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Activity_Monitoring', '0004_auto_20190418_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(db_column='is_finished', default=False, verbose_name=['django.contrib.auth.backends.ModelBackend', 'field_permissions.backends.InstancePermissionBackend']),
        ),
    ]
